# Generated by Django 3.1.3 on 2020-11-04 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expirince',
            new_name='Experince',
        ),
    ]
