# Generated by Django 3.1.3 on 2020-11-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20201105_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experince',
            name='date',
            field=models.DateField(),
        ),
    ]
