# Generated by Django 3.1.3 on 2020-11-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20201105_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='one_line',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
