# Generated by Django 3.1.3 on 2020-11-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_settings_one_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='family',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
