# Generated by Django 3.1.3 on 2020-11-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_settings_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills_tools',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='skills_tools',
            name='title',
        ),
        migrations.AddField(
            model_name='skills_tools',
            name='Class',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
