# Generated by Django 3.1.3 on 2020-11-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_settings_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills_tools',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
