# Generated by Django 3.1.3 on 2020-11-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_skills_tools_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='guthub',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
