# Generated by Django 3.1.3 on 2020-11-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20201105_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='guthub',
            new_name='github',
        ),
    ]
