# Generated by Django 3.1.3 on 2020-11-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20201105_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills_tools',
            name='Class',
        ),
        migrations.AddField(
            model_name='skills_tools',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
