# Generated by Django 3.1.3 on 2020-11-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20201105_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experince',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='tools',
            old_name='titile',
            new_name='title',
        ),
    ]
